param(
 [ValidateSet('menu','status','uptime','start','stop','restart','install-service','remove-service','migrate-service','setup','production-repair','db-test','migrate','dependency-test','dependency-install','port','logs','health','check-update','update','rollback','version','doctor','help')][string]$Action='menu',[string]$Value=''
)
$ErrorActionPreference='Stop';$Root=Split-Path $PSScriptRoot -Parent;$M=Get-Content -Raw (Join-Path $Root 'project-control.json')|ConvertFrom-Json;$State=Join-Path $Root 'runtime\project-control\release-state.json'
function Fail($m){Write-Host "ERROR: $m" -ForegroundColor Red;exit 1}
function Admin{$p=New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent());if(-not$p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){Fail 'Run PROJECT-CONTROL.bat from an Administrator terminal.'}}
function Confirm($q){Write-Host "`n$q" -ForegroundColor Yellow;$a=(Read-Host '[Y] Yes  [N/Enter/any other key] Cancel').Trim();if($a -match '^(?i:y|yes)$'){return $true};Write-Host 'Cancelled. Returning to the menu.' -ForegroundColor DarkYellow;$script:MenuCancelled=$true;return $false};function WaitForMenu{Write-Host "`nPress any key to return to the menu..." -ForegroundColor DarkGray;[void][Console]::ReadKey($true)}
function Ver{(Get-Content -Raw (Join-Path $Root 'package.json')|ConvertFrom-Json).version}
function Port{$p=[int]$M.defaultPort;$e=Join-Path $Root '.env';if(Test-Path $e){$l=Get-Content $e|Where-Object{$_-match'^\s*PORT\s*=\s*(\d+)'}|Select-Object -Last 1;if($l-match'(\d+)'){$p=[int]$Matches[1]}};$p}
function Health{try{Invoke-RestMethod "http://127.0.0.1:$(Port)$($M.healthPath)" -TimeoutSec 8}catch{$null}}
function Svc($id=$M.serviceId){Get-Service -Name $id -ErrorAction SilentlyContinue}
function Listener{Get-NetTCPConnection -State Listen -LocalPort (Port) -ErrorAction SilentlyContinue|Select-Object -First 1}
function Ports{$l=Listener;Write-Host "HTTP port        : $(Port)";Write-Host "HTTP listener    : $(if($l){"LISTENING (PID $($l.OwningProcess))"}else{'not listening'})";Write-Host 'PostgreSQL port  : external dependency; not managed by this controller'}
function Status{$s=Svc;$old=Svc $M.legacyServiceId;$h=Health;Write-Host 'Project          : CAMPEROS-ACCOUNTING';Write-Host "Installed version: $(Ver)";Write-Host "Service          : $($M.serviceName)";Write-Host "Service ID       : $($M.serviceId)";Write-Host "Service state    : $(if($s){$s.Status}else{'not installed'})";Write-Host "Legacy service   : $(if($old){$old.Status}else{'not installed'})";Write-Host "Health           : $(if($h){'ok'}else{'unreachable'})";if($h){Write-Host "PID              : $($h.process.pid)";Write-Host "Uptime           : $([TimeSpan]::FromMilliseconds($h.process.uptimeMs))";Write-Host "Database         : $($h.database)"};Write-Host '';Ports}
function StopRuntime{Admin;$s=Svc;if($s){Set-Service $M.serviceId -StartupType Disabled;if($s.Status-ne'Stopped'){Stop-Service $M.serviceId -Force;try{$s.WaitForStatus('Stopped',[TimeSpan]::FromSeconds(45))}catch{}}};$h=Health;if($h){$l=Listener;$pidValue=[int]$h.process.pid;if(-not$l-or[int]$l.OwningProcess-ne$pidValue){Fail 'Health PID does not own the Camperos HTTP port.'};Stop-Process -Id $pidValue -Force -ErrorAction SilentlyContinue;Start-Sleep 2};if(Health){Fail 'Camperos Accounting still answers after stop.'};Write-Host 'Camperos Accounting is stopped and disabled until Start or Restart.' -ForegroundColor Green;Status}
function StartRuntime{Admin;$s=Svc;if(-not$s){Fail '0-CAMPEROS-ACCOUNTING is not installed.'};Set-Service $M.serviceId -StartupType Automatic;if($s.Status-ne'Running'){Start-Service $M.serviceId};$until=(Get-Date).AddSeconds(60);do{Start-Sleep 1;$h=Health}while(-not$h-and(Get-Date)-lt$until);if(-not$h){Fail 'Camperos Accounting did not become healthy. Check logs and database.'};Status}
function RestartRuntime{StopRuntime;StartRuntime}
function Install{Admin;if(-not(Test-Path (Join-Path $Root 'node_modules\node-windows'))){Fail 'Dependencies missing. Run option 24.'};& node (Join-Path $Root 'scripts\windows-service.js') install;if($LASTEXITCODE){exit $LASTEXITCODE};Start-Sleep 3;Write-Host 'Installed 0-CAMPEROS-ACCOUNTING. Select Start when ready.'}
function Remove{Admin;if(Svc){StopRuntime};& node (Join-Path $Root 'scripts\windows-service.js') uninstall;if($LASTEXITCODE){exit $LASTEXITCODE}}
function SetPort{if(-not$Value){Ports;return};$n=0;if(-not[int]::TryParse($Value,[ref]$n)-or$n-lt1-or$n-gt65535){Fail 'Port must be 1-65535.'};$e=Join-Path $Root '.env';if(-not(Test-Path $e)){Fail '.env missing. Run option 19.'};Copy-Item $e "$e.project-control-backup" -Force;$lines=@(Get-Content $e);$found=$false;$lines=@($lines|ForEach-Object{if($_-match'^\s*PORT\s*='){$found=$true;"PORT=$n"}elseif($_-match'^\s*APP_ORIGIN\s*='){"APP_ORIGIN=http://localhost:$n"}else{$_}});if(-not$found){$lines+="PORT=$n"};Set-Content $e $lines -Encoding UTF8;Write-Host "HTTP port set to $n. Restart to apply." -ForegroundColor Green}
function Clean{if(@(& git -C $Root status --porcelain).Count){Fail 'Checkout has uncommitted changes.'}}
function Latest{& git -C $Root tag --list $M.releaseTagPattern --merged "origin/$($M.releaseBranch)" --sort=-version:refname|Select-Object -First 1}
function CheckUpdate{& git -C $Root fetch origin $M.releaseBranch --tags --prune;if($LASTEXITCODE){Fail 'Git fetch failed.'};$c=& git -C $Root describe --tags --exact-match HEAD 2>$null;Write-Host "Current: $(if($c){$c}else{& git -C $Root rev-parse --short HEAD})";Write-Host "Latest : $(Latest)";Write-Host "Branch : $($M.releaseBranch)"}
function Update{Clean;CheckUpdate;$tag=Latest;if(-not$tag){Fail 'No release tag found.'};New-Item -ItemType Directory (Split-Path $State) -Force|Out-Null;@{previous=(& git -C $Root rev-parse HEAD);target=$tag}|ConvertTo-Json|Set-Content $State;& git -C $Root checkout --detach $tag;if($LASTEXITCODE){exit $LASTEXITCODE};& npm ci;if($LASTEXITCODE){exit $LASTEXITCODE};& npm run db:migrate;if($LASTEXITCODE){exit $LASTEXITCODE};Doctor;if(Svc){RestartRuntime}}
function Rollback{Clean;if(-not(Test-Path $State)){Fail 'No rollback state recorded.'};$x=Get-Content -Raw $State|ConvertFrom-Json;& git -C $Root checkout --detach $x.previous;if($LASTEXITCODE){exit $LASTEXITCODE};& npm ci;if($LASTEXITCODE){exit $LASTEXITCODE};if(Svc){RestartRuntime}}
function DbTest{& npm run db:test;exit $LASTEXITCODE}
function Dependencies{& npm ci;exit $LASTEXITCODE}
function DepTest{& npm ls --all;exit $LASTEXITCODE}
function Doctor{foreach($c in @('git','node','npm','powershell.exe')){if(Get-Command $c -ErrorAction SilentlyContinue){Write-Host "[OK] $c" -ForegroundColor Green}else{Fail "$c missing."}};if(-not(Test-Path (Join-Path $Root '.env'))){Fail '.env missing.'};& node --check (Join-Path $Root 'app.js');if($LASTEXITCODE){exit $LASTEXITCODE};& npm run staging:check;exit $LASTEXITCODE}
function Setup{if(-not(Test-Path (Join-Path $Root '.env'))){Copy-Item (Join-Path $Root '.env.example') (Join-Path $Root '.env');Write-Host 'Created .env from example; configure database password and secrets.' -ForegroundColor Yellow};Remove-Item -LiteralPath (Join-Path $Root 'dist\Home-Accounting-Manager.bat') -Force -ErrorAction SilentlyContinue;& npm ci;exit $LASTEXITCODE}
function Repair{Setup;DbTest;& npm run db:migrate;if($LASTEXITCODE){exit $LASTEXITCODE};if(Svc){RestartRuntime}}
function MigrateManager{Admin;$h=Health;if($h){$l=Listener;if(-not$l-or[int]$l.OwningProcess-ne[int]$h.process.pid){Fail 'Refusing to stop an unverified process.'};Stop-Process -Id ([int]$h.process.pid) -Force;Start-Sleep 2};$old=Svc $M.legacyServiceId;if($old){if($old.Status-ne'Stopped'){Stop-Service $M.legacyServiceId -Force};sc.exe delete $M.legacyServiceId|Out-Null;Start-Sleep 2};if(Svc){Remove;Start-Sleep 2};Install;StartRuntime}
function Logs{$f=Get-ChildItem (Join-Path $Root 'logs\*.log'),(Join-Path $Root 'daemon\*.log') -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if(-not$f){Fail 'No logs found.'};Write-Host "Log: $($f.FullName)";Get-Content $f.FullName -Tail 100}
function Run($a,$v=''){$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-Action',$a);if($v){$args+=@('-Value',$v)};& powershell.exe @args;$code=$LASTEXITCODE;Write-Host "`n$(if($code-eq0){'Command completed successfully.'}else{"Command failed with exit code $code."})" -ForegroundColor $(if($code-eq0){'Green'}else{'Red'})}
function Menu{while($true){Clear-Host;Write-Host '========== CAMPEROS ACCOUNTING PROJECT CONTROL ==========' -ForegroundColor Cyan;Write-Host ' INFORMATION' -ForegroundColor Cyan;Write-Host '  1. Status                    2. Uptime';Write-Host '  3. Health details            4. Version information';Write-Host '  5. View logs                 6. Run doctor/validation';Write-Host '  7. Show configured ports     8. Check for release update';Write-Host '';Write-Host ' RUNTIME CONTROL' -ForegroundColor Green;Write-Host '  9. Start                    10. Stop';Write-Host ' 11. Restart                  12. Install service/runtime';Write-Host ' 13. Remove service/runtime';Write-Host '';Write-Host ' CONFIGURATION AND RELEASES' -ForegroundColor Yellow;Write-Host ' 14. Change ports             15. Install latest release';Write-Host ' 16. Roll back release        17. Command help';Write-Host ' 18. Migrate legacy manager';Write-Host '';Write-Host ' SETUP AND DEPENDENCIES' -ForegroundColor Magenta;Write-Host ' 19. Project setup            20. Production setup/repair';Write-Host ' 21. Test database/storage    22. Run migrations';Write-Host ' 23. Test dependencies        24. Install/repair dependencies';Write-Host '';Write-Host '  0. Exit';$c=(Read-Host 'Select a menu number').Trim();switch($c){'0'{return};'1'{Run status};'2'{Run uptime};'3'{Run health};'4'{Run version};'5'{Run logs};'6'{Run doctor};'7'{Run port};'8'{Run check-update};'9'{Run start};'10'{if(Confirm 'Stop Camperos Accounting?'){Run stop}};'11'{if(Confirm 'Restart Camperos Accounting?'){Run restart}};'12'{if(Confirm 'Install 0-CAMPEROS-ACCOUNTING?'){Run install-service}};'13'{if(Confirm 'Remove 0-CAMPEROS-ACCOUNTING?'){Run remove-service}};'14'{$p=Read-Host 'New HTTP port';Run port $p};'15'{if(Confirm 'Install latest tagged release?'){Run update}};'16'{if(Confirm 'Roll back release?'){Run rollback}};'17'{Run help};'18'{if(Confirm 'Migrate legacy manager?'){Run migrate-service}};'19'{if(Confirm 'Run project setup?'){Run setup}};'20'{if(Confirm 'Run production setup/repair?'){Run production-repair}};'21'{Run db-test};'22'{if(Confirm 'Run database migrations?'){Run migrate}};'23'{Run dependency-test};'24'{if(Confirm 'Install exact dependencies?'){Run dependency-install}};default{Write-Host 'Invalid selection.' -ForegroundColor Red}};if($script:MenuCancelled){$script:MenuCancelled=$false;continue};WaitForMenu}}
Set-Location $Root
switch($Action){menu{Menu};status{Status};uptime{$h=Health;if(-not$h){Fail 'Unreachable.'};[TimeSpan]::FromMilliseconds($h.process.uptimeMs)};start{StartRuntime};stop{StopRuntime};restart{RestartRuntime};'install-service'{Install};'remove-service'{Remove};'migrate-service'{MigrateManager};setup{Setup};'production-repair'{Repair};'db-test'{DbTest};migrate{& npm run db:migrate;exit $LASTEXITCODE};'dependency-test'{DepTest};'dependency-install'{Dependencies};port{SetPort};logs{Logs};health{$h=Health;if(-not$h){Fail 'Unreachable.'};$h|ConvertTo-Json -Depth 5};'check-update'{CheckUpdate};update{Update};rollback{Rollback};version{Write-Host "Installed: $(Ver)";$h=Health;Write-Host "Running  : $(if($h){$h.version}else{'unreachable'})"};doctor{Doctor};help{Write-Host 'Use PROJECT-CONTROL.bat for all runtime, database, dependency, and release operations.'}}
